[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.108.0"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/blog"
  to = "/newsletter"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/writing-newsletter"
  to = "https://view.flodesk.com/pages/6438556c47fd69214ac03f1d"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/writingcourse"
  to = "https://www.chicourse.com/courses/how-to-write-better-research-papers"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"

[[redirects]]
  from = "/newsletter/2023/06/27/introducing-the-game-ux-pyramid-navigating-player-needs/"
  to = "/newsletter/2023/06/27/the-game-ux-design-pyramid-applying-the-ux-pyramid-to-ux-game-design/"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}